const locale = {
  newChat: 'New Chat',
  setting: 'Settings',
  responseLength: 'Response Length',
  temperature: 'Temperature',
  topP: 'TopP',
  topK: 'TopK',
  confirm: 'Confirm',
  cancel: 'Cancel',
  inputPlaceholder: 'Enter the content you want to know, use Shift+Enter for line breaks.',
  copySuccess: 'Copy successful.',
  welcomeHeader: 'I am YuanChat, a dialogue application based on Yuan 2.0 large language model.',
  welcomeParagraph1:
    'I am capable of engaging in multi-turn conversations, answering domain-specific questions, and assisting individuals in application writing and artistic creation.',
  deleteConversationConfirm: 'Are you sure you want to delete this conversation?',
  send: 'Send',
  recommend: 'Recommended questions',
  refresh: 'Refresh',
  stopTyping: 'Stop',
  language: 'Language',
  'max-multi-turns': 'Multiple dialogue rounds',
  noEmpty: 'Can not be empty',
  sources: 'Sources',
  related: 'Related',
  wsEnabled: 'Web Search Engine Enabled',
  wsDisabled: 'Web Search Engine Disabled',
  wsConfigSetting: 'Web Search Config',
  embeddingModelPath: 'Embedding Model Path',
  sourceTopK: 'Source TopK',
  llmTemplate: 'LLM Template',
  disclaimer:
    'All content is generated by AI models and is for reference only. It does not represent our attitudes or opinions. Please abide by ',
  and: 'and'
}

export default locale
