serper_api_key: "e4e726300b3804897d394c87fc50aa81357015b5"
openai_api_key: "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"
model_name: "yuan2"
template: |    
  Web搜索结果：
  {context_str}
  说明：您是一位{profile}。使用提供的网络搜索结果，对给定的问题写一个全面而详细的回复。
  用语言回答：{language}
  问题：{query}
  答案：


